openapi: "3.1.0"
info:
  title: "todo API"
  description: "todo API"
  version: "1.0.0"
servers:
  - url: http://localhost:8080/api
    description: Test
paths:
  /:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
  /todo/auth/login:
    post:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /todo/auth/me:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
  /todo/tasks:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Task"
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
        required: true
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                type: "integer"
                format: "int64"
  /todo/tasks/{id}:
    delete:
      description: ""
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
      responses:
        "204":
          description: "No Content"
          content:
            '*/*':
              schema:
                type: "object"
    get:
      description: ""
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Task"
    patch:
      description: ""
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
        required: true
      responses:
        "204":
          description: "No Content"
          content:
            '*/*':
              schema:
                type: "object"
    put:
      description: ""
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
        required: true
      responses:
        "204":
          description: "No Content"
          content:
            '*/*':
              schema:
                type: "object"
components:
  schemas:
    Task:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          nullable: true
        name:
          type: "string"
          nullable: true
        note:
          type: "string"
          nullable: true
        isCompleted:
          type: "boolean"
          nullable: true
        isImportant:
          type: "boolean"
          nullable: true
        createdAt:
          type: "string"
          format: "date-time"
          nullable: true
        createdById:
          type: "integer"
          format: "int64"
          nullable: true