spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cool
    username: postgres
    password: 12as!@AS
  jpa:
    show-sql: on

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,flyway
logging:
  level:
    org.springframework.security: trace
