spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cool
    username: postgres
    password: 12as!@AS

  jpa:
    show-sql: on
logging:
  level:
    org.springframework.security: Trace
