openapi: 3.0.3
info:
  title: Cool
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Local server
tags:
  - name: sys
    description: 系统
  - name: todo
    description: 待办事项

paths:
  /todo/tasks:
    get:
      tags:
        - todo
      summary: 查询待办事项
      operationId: listTasks
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    name:
                      type: string
                      description: 任务名称
                      example: 任务1
                    note:
                      type: string
                      description: 任务备注
                      example: 备注1
    post:
      tags:
        - todo
      summary: 新增待办事项
      operationId: createTask
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 任务名称
                  example: 任务1
                note:
                  type: string
                  description: 任务备注
                  example: 备注1

      responses:
        200:
          description: OK